### ISSUE TITLE
meteor build folder goes crazy at second run and meteor does not start

### ISSUE THREAD

**Issue by serkandurusoy** [sdarnell/meteor-win#10]
When I have a clean .meteor/local directory or when I have only the db directory inside, I can run meteor.

But if I stop (ctrl+c) and restart, one of two things happen:

1) if I run cmd as a regular user, mongodb does not stop with ctrl+c and therefore I get address conflict errors

2) if I run cmd as administrator, the **build** directory gets renamed as **.build.build** and meteor does not start. Also an error is thrown:

``` javascript
No dependency info in bundle. Filesystem monitoring disabled.
=> Errors prevented startup:
Exception while bundling application:
Error: EPERM, operation not permitted 'c:\Users\serkandurusoy\Documents\MeteorApps\capulcuyuzbiz\.meteor\local\.build.build'
    at Object.fs.renameSync (fs.js:439:18)
    at _.extend.write_to_directory (C:\Program Files (x86)\Meteor\tools\bundler.js:833:8)
    at Object.exports.bundle (C:\Program Files (x86)\Meteor\tools\bundler.js:911:12)
    at C:\Program Files (x86)\Meteor\tools\run.js:695:26
    at exports.inFiber (C:\Program Files (x86)\Meteor\tools\fiber-helpers.js:24:12)

Please fix the problem and restart.
```

If I delete the .build.build directory, I can restart.

But since hot code reload does not work either, such a workflow of having to stop server delete directories and start back up becomes a heavy burden.

**Comment by sdarnell** [comment]
I've not seen any problem killing mongod for quite a few versions - which version are you using?
Exactly what is the error you are seeing with the "address conflict error" - is it EADDRINUSE from meteor or a mongo specific error?

The way that the bundling works is to build the files into a temporary **.build.build** directory, that is then renamed to just **build**. This ensures that the build directory only ever contains a coherent and complete set of files.

The EPERM error is occurring at the very end at the final rename. This suggests to me that:
1. there is an existing **build**  directory
2. something still has a file open in the **.build.buid** directory

For 1. my guess is that there could be a node.exe (meteor) or mongod process still running. Please check using task manager, command prompt tasklist or Powershell Get-Process.

For 2. the cause is possibly the Windows search rummaging in the new directory, or a virus checker examining the fresh files that have just appeared.
Maybe you could try disabling them temporarily to see if that helps. 

I would also suggest you try the latest release 0.6.3.1-rev4 which includes an improvement to terminating the child meteor processes. Make sure you uninstall the existing version first, assuming you're on 0.6.3+ already.

**Comment by serkandurusoy** [comment]
I added mongod.exe to windows firewall as well as meteor ports. This resolved the problem about mongod process not exiting together with meteor.

About the eperm error, having the .meteor/local directory open in windows explorer has this adverse effect. If it is not open in windows explorer, (I was actually trying to observe meteor's build process for any differences to linux if any) than there is no problem.
