### ISSUE TITLE
Add to path

### ISSUE THREAD

**Issue by ChrisMiami** [sdarnell/meteor-win#11]
Installer should add the installed folder to the path environment variable, as the "Getting Started" doc does not include this as a step, so it should be able to be assumed, and the next step after installing would then be "Open a command window and enter 'meteor create myapp':.

**Comment by sdarnell** [comment]
The installer does add the meteor installation directory to your PATH (system)
Of course it does not take effect until you open a new command prompt.

Here's what I get after installation:
![image](https://f.cloud.github.com/assets/3684334/637471/d6f76a7a-d2a4-11e2-9b83-372172c03348.png)
and then at the end of the Path entry:
![image](https://f.cloud.github.com/assets/3684334/637480/3c372dc6-d2a5-11e2-84e6-c8ff7f78246b.png)

When I create a new command prompt and type `set path` apart from tonnes of other junk I can see the Meteor entry at the end.

Could it be that you have settings that override it?

**Comment by ChrisMiami** [comment]
That's interesting.  Of course, I tried opening both Cygwin shell and cmd shell, but the setting wasn't available in either.  Just now, I checked and indeed the settings you noted were there, but they did not take effect for some reason.  I do have a path override in my User variables list (its first entry is %Path%), and wasn't able to run meteor until I added it to the end of that.

After your note I removed my values and tested again (with 2 changes) and they work.

The changes I made (which I recommend) were (a) remove the trailing slash from the Meteor_Path and then (b) use %Meteor_Path% in the Path variable rather than another copy of the literal.

**Comment by sdarnell** [comment]
Glad that sorted things out, and I appreciate the suggested change of using METEOR_PATH - I'll give it a whirl.

**Comment by sdarnell** [comment]
FWIW I researched the question of removing the final slash and indirecting with %METEOR_PATH% instead of repeating the path.

Removing the slash is far from trivial in Wix/MSIs - the only reasonable option would be to add a bin directory. But this seems devalue any benefit. There is also the question of backwards compatibility - someone might be relying on the trailing slash.

Referencing another environment variable from the Path seems to be fraught with possible problems, given **M** is before **P** it should be OK, but there seem to be reports on different forums of platform differences, and I can't really justify the risk - even if it seems to work for me. By _risk_ I mean support effort if it doesn't work somewhere.
