### ISSUE TITLE
Error while installation (0.6.5 LaunchMeteor.exe) - PathTooLongException

### ISSUE THREAD

**Issue by minicuper** [sdarnell/meteor-win#16]
I've got the listing:

```
Downloading initial Meteor files...
100 ###############################################################
Download complete (29,9 MB)
Extracting files to C:\Users\1\AppData\Local\.meteor
...............................................................................
...............................................................................
...............................................................................
..............................................................................
expected exception: System.IO.PathTooLongException: Слишком длинный путь или им файла. 
Полное имя файла должно содержать меньше 260 знаков, а имя каталога -
 меньше 248 знаков.
   в System.IO.Path.SafeSetStackPointerValue(Char* buffer, Int32 index, Char va
ue)
   в System.IO.Path.NormalizePathFast(String path, Boolean fullCheck)
   в System.IO.Path.GetDirectoryName(String path)
   в LaunchMeteor.Program.ExtractTgz(Stream stream, String directory)
   в LaunchMeteor.Program.BootstrapWarehouse(String warehouse)
   в LaunchMeteor.Program.Main(String[] args)

Please press any key to exit.
```

The message is in russian, in english that means: "The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248"

After that the installation is interrupted.
P.S. Windows 7 64bit (starting LaunchMeteor.exe from c:\1\LaunchMeteor.exe)

**Comment by sdarnell** [comment]
Out of interest, is your C: drive NTFS?

I'll prepare a version of `LaunchMeteor.exe` with some extra debugging in, but there are a couple of work-arounds:

First, set an environment variable `METEOR_WAREHOUSE_DIR` to a short path, for example `c:\1\x` and create that directory, before running the `LaunchMeteor.exe` again. This environment variable acts as an override and should help if the issue is overall path length.

Another work-around is to extract the bootstrap tarball yourself. The bootstrap tarball can be found [here](https://win-install.meteor.com/bootstrap/meteor-bootstrap-Windows_i686.tar.gz)

**Comment by minicuper** [comment]
NTFS
First way did't help:

```
'C:\1\x' exists, but does not contain a meteor.bat

Remove it and try again.

Please press any key to exit.
```

**Comment by sdarnell** [comment]
Sorry, my advice to create `c:\1\x` was wrong. `METEOR_WAREHOUSE_DIR` needs to point at a directory that doesn't exist yet (or a fully populated warehouse). So just delete the directory and try again.  Sorry for the incorrect info.

**Comment by sdarnell** [comment]
For reference, the longest path in the warehouse seems to be related to node-gyp - but severely aggravated by the way meteor includes dependencies and uses a longish 'node_modules' prefix each time. It ends up being 231 chars, excluding the warehouse location. So that only leaves 260 - 212 = 48 characters.

Your path `C:\Users\1\AppData\Local\.meteor` is only 32 characters, but internally it creates a temporary directory by appending `-install-tmp` which is another 12 chars, totalling 44.

So it looks like it is very close :( 

If nothing else I can rescue maybe 10 characters from the suffix I add, but it may be possible to switch the code over to using relative path names.

**Comment by minicuper** [comment]
Ok. I deleted "c:\1\x" and it helped. Thank you!

**Comment by sdarnell** [comment]
Glad this work-around worked.

I'll reopen this bug for now as I'd like to make some improvements, as I suspect too many people will hit this limit.

**Comment by minicuper** [comment]
> I suspect too many people will hit this limit.

I think so. My windows username - "1" have quite a small length.

**Comment by sdarnell** [comment]
By the way, while investigating I spotted that the temporary directory doesn't get deleted.
I suspect you will have a `C:\Users\1\AppData\Local\.meteor-install-tmp` directory doing no good.

**Comment by minicuper** [comment]
I noticed the feature and deleted it manually.

**Comment by sdarnell** [comment]
:) by the way I discovered that the exact limit is currently 27 characters the warehouse directory limit, so subtracting the `/.meteor` that leaves only... 19 characters for `LOCALAPPDATA`, which is hardly anything.

**Comment by sdarnell** [comment]
I've improved the situation and re-released. Now the longest file in the bootstrap package is 190 characters (including the .meteor prefix). Only one character is used as a temporary indicator, and a slash separator, so there should be 260 - 192 = 68 characters for the `LOCALAPPDATA` path. Given the default convention for `LOCALAPPDATA` I think that leaves about 45 chars for the username.

Still tight, but far better. I'll close for now.
