### ISSUE TITLE
Can't run meteor from terminal anymore

### ISSUE THREAD

**Issue by dimfisch** [sdarnell/meteor-win#18]
I uninstalled METEOR 0.6.4 and then installed 0.6.5 as described on https://github.com/sdarnell/meteor/wiki/Windows
Now when I try to run "meteor" from command line in a terminal I get the following error: bash.exe": meteor: command not found
Should I specify what program meteor should link to? How?

**Comment by sdarnell** [comment]
Previously there was a wrapper `meteor` bash shell script which no longer exists, but the remaining `meteor.bat` should work for cygwin-like environments.

My guess is that there are a few things that might be happening:
1. Your console is a pre-existing console, started before you did the install, and therefore hasn't picked up the new PATH entry. **Solution:** Try starting a new console and see if that works.
2. The cygwin console hasn't picked up the new PATH entry for some reason. For example if you explicitly set your path in a .profile script etc. this may be overriding the new entry. **Solution:** Check the PATH variable in your console and if necessary add it explicitly. You may need to specify it with something like `/c/users/dimfisch/AppData/Local/.meteor/bin`.
3. The shell you are running is not automatically running batch files.  Try running `meteor.bat` instead of just `meteor`.  **Solution:** If this is the case we can add a simple bash compatible wrapper that does the right thing.

**Comment by dimfisch** [comment]
Not sure what's happening here:

```
dimfisch@DIMFISCH-PC ~/Documents/Patio/patio (master)
$ meteor
bash.exe": meteor: command not found

dimfisch@DIMFISCH-PC ~/Documents/Patio/patio (master)
$ meteor.bat
/c/Users/dimfisch/AppData/Local/.meteor/meteor.bat: line 1: @echo: command not found
/c/Users/dimfisch/AppData/Local/.meteor/meteor.bat: line 2: setlocal: command not found
/c/Users/dimfisch/AppData/Local/.meteor/meteor.bat: line 4: syntax error near unexpected token `('
/c/Users/dimfisch/AppData/Local/.meteor/meteor.bat: line 4: `if exist "%_METEOR_ROOT_%.git" ('
```

It seems to recognize meteor.bat but then something goes wrong, right?

**Comment by sdarnell** [comment]
Hmmm, not sure. As a temporary measure could you try running meteor from a regular  DOS command prompt?

**Comment by dimfisch** [comment]
Yes, Meteor is running from DOS command. I was using Git Shell before. Why do you think it doesn't work there?

**Comment by sdarnell** [comment]
I did a bit more investigation and the underlying problem seems to be an inability of msys/mingw to run bat files on the PATH. I find it somewhat bizarre that it doesn't work (in a similar way that .exe's are handled), and seems to be considered an enhancement request.
Here is the corresponding bug report: http://sourceforge.net/p/mingw/bugs/1902/
And here's the msysgit relevant bug: https://code.google.com/p/msysgit/issues/detail?id=426

As it happens I seem to be able to get it to invoke using: `cmd.exe //C meteor.bat`

So I suspect we could add a bash script wrapper that does this (and passes any additional arguments too).

However, I wonder whether a better option is to use a .exe and as it happens, `LaunchMeteor.exe` can be used in that way.  Please could you try copying the `LaunchMeteor.exe` executable to `%LOCALAPPDATA%\meteor.exe` and then see if that works for you.

**Comment by dimfisch** [comment]
By `LaunchMeteor.exe` you mean the file I downloaded from your repo that installs Meteor on Windows?

**Comment by sdarnell** [comment]
Yes, that's right. This executable downloads the bootstrap bundle if you haven't downloaded it already, and then invokes meteor normally (in the same way as meteor.bat).

**Comment by DavidCRivera** [comment]
Thanks for clarifying. I just tested this and it works. (I was having the same problem and had been using CMD)
No problem using GIT Bash to initiate Meteor once I followed those directions now.

**Comment by dimfisch** [comment]
Yes, it now works for me too on Git Shell :)
Thanks

**Comment by sdarnell** [comment]
Just a quick update. As of windows meteor 0.8.3 there is a meteor.exe file along side the meteor.bat (which is just a copy of LaunchMeteor.exe). But this should avoid the cygwin issue.
Note that it will only appear on a fresh install, not an update.

**Comment by lukemadera** [comment]
@sdarnell I just installed v0.1.7 and I don't see a `meteor.exe` in the `.meteor` folder. When I try copying and renaming `LaunchMeteor.exe`, I get this error: 

``` bash
Unexpected exception: System.IO.DirectoryNotFoundException: Could not find a par
t of the path 'C:\Users\LukeM\AppData\Local\.meteor\tools\latest'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detec
tEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path, Encoding encoding)
   at LaunchMeteor.Program.Main(String[] args)
```

Also, `.meteor` was NOT added to my PATH - I had to do that manually.

Any ideas / suggestions as to how I get can meteor running on Windows through Git Bash?

**Comment by peterennis** [comment]
Are you referring to Windows Preview 0.1.7 from here?:
https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows

I downloaded that and it worked. It is the official port and questions related
to it are best sent to their list.

Maybe @sdarnell can provide more wisdom...

**Comment by lukemadera** [comment]
Yes @peterennis - so it worked for you on Git Bash? What version of Git Bash are you on - could that be the issue?

**Comment by peterennis** [comment]
```
peterennis@W81 ~
$ git --version
git version 1.9.5.msysgit.0
```

**Comment by sdarnell** [comment]
The problem is that msysgit and gitbash do not find and execute .bat files. So the MDG Preview 0.1.7 uses a batch file so this will hit the issue. Really you need to raise issues on:
https://github.com/meteor/meteor/wiki/Preview-of-Meteor-on-Windows
(EDIT: The issue tracker is at : https://github.com/meteor/windows-preview)
But I have already suggested that a standard .exe is needed.
My port switched to using a meteor.exe.

The other alternative is to have a shell script in the right location which mirrors the batch file, and if you use gitbash/msysgit this may be sufficient.  However there are other issues with batch files, such as the Ctrl+C producing the 'Do you want to terminate... Y/N' question.

**Comment by sdarnell** [comment]
As for the `%LOCALAPPDATA%\.meteor` not being added to your PATH. Are you sure? I suspect it is adding to the PATH but you haven't created a new process.
If you are sure, then again you would need to raise it on the MDG preview issue tracker (as there have been significant changes to the port since mine).
Having said that, I know there are plans to replace the installer and this should reduce some of the installation issues, however the MSI file will edit the PATH in pretty much the same way as the InstallMeteor.exe does.

**Comment by lucaspereira06** [comment]
run as administrator

**Comment by sdarnell** [comment]
There's absolutely no need to run as administrator, and it is generally bad practice (insecure) to do so.
