### ISSUE TITLE
Crashing when creating an application

### ISSUE THREAD

**Issue by Gornova** [sdarnell/meteor-win#4]
hi!
My system: windows xp sp3.

Test case:
1) downloaded last version from here: https://github.com/sdarnell/meteor/wiki/Windows
2) installed
3) followed README.md and created a project with meteor create try-meteor and then 
    cd try-meteor / meteor

Problem: 
1) on console and from web page I have so far:

Your app is crashing. Here's the latest log.

F:\progettiMeteor\test.meteor\local\build\server\server.js:325
  }).run();
     ^
Error: Can't find npm module 'sockjs'. Did you forget to call 'Npm.depends' in package.js within the 'livedata' package?
    at Object._.each.Npm.require (F:\progettiMeteor\test.meteor\local\build\server\server.js:259:23)
    at new Meteor._DdpStreamServer (app/packages/livedata/stream_server.js:18:20)
    at new Meteor._LivedataServer (app/packages/livedata/livedata_server.js:1002:24)
    at app/packages/livedata/server_convenience.js:8:19
    at F:\progettiMeteor\test.meteor\local\build\server\server.js:286:12
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Programmi\Meteor\lib\node_modules\underscore\underscore.js:79:11)
    at run (F:\progettiMeteor\test.meteor\local\build\server\server.js:227:7)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

note: this problem is also on example project.

thanks!

**Comment by sdarnell** [comment]
OK, unfortunately I don't have an XP system to test it on. I have done a fresh install of Meteor 0.6.2.1 on Win7 x64 and it is fine.
But hopefully we can narrow things down a bit.

Is it 32-bit or 64 bit OS? Home, or Pro ? (not sure it will make any difference, but possibly)
Have you previously installed any other versions of Meteor?
Did you install it to a non default location?

Do you have a directory (assuming 32bit):
  `"c:\Program Files\Meteor\packages\livedata\.npm\node_modules\sockjs"`
or for 64-bit:
  `"c:\Program Files (x86)\Meteor\packages\livedata\.npm\node_modules\sockjs"`

If they do no exist, are there any subdirectories in that node_modules directory? There should be sockjs and websocket.

From console prompt, what answer do you get for:
`c:\> where meteor`

Otherwise we may need to put some extra debugging into see why it can't find the right files.

As a temporary measure you might try uninstalling 0.6.2.1 and installing version 0.5.9, and then replacing the fibers.node file with the version linked on the download page. (The file goes in program files Meteor\lib\node_modules\fibers).

**Comment by Gornova** [comment]
OS: 32bit, Professional
Previous version of meteor: no, first install
Location: default on C:\Programmi\Meteor (I'm italian, so Programmi => Program Files)
From here: C:\Programmi\Meteor\packages\livedata.npm\node_modules\sockjs I have:

.npmignore
.pidfile.pid
Changelog
COPYING
examples
index.js
lib
LICENSE-MIT-SockJS
Makefile
node_modules
package.json
README.md

where: where is not a recognized program

**Comment by sdarnell** [comment]
Please could you add a trace statement to:
  c:\Programmi\Meteor\tools\server\server.js just before line 252

```
250:              name);
251:
new:  console.log("### '%s'", nodeModuleDir);
252:            if (fs.existsSync(nodeModuleDir)) {
```

Then re-run to see what that produces.

**Comment by Gornova** [comment]
Done, here my report:

[[[[[ F:\progettiMeteor\todos ]]]]]

=> Meteor server running on: http://localhost:3000/

### 'F:\progettiMeteor\todos.meteor\local\build\app\packages\meteor\node_module

s\path'

F:\progettiMeteor\todos.meteor\local\build\server\server.js:325
  }).run();
     ^
Error: Can't find npm module 'sockjs'. Did you forget to call 'Npm.depends' in p
ackage.js within the 'livedata' package?
    at Object._.each.Npm.require (F:\progettiMeteor\todos.meteor\local\build\se
rver\server.js:259:23)
    at new Meteor._DdpStreamServer (app/packages/livedata/stream_server.js:18:20
)
    at new Meteor._LivedataServer (app/packages/livedata/livedata_server.js:1002
:24)
    at app/packages/livedata/server_convenience.js:8:19
    at F:\progettiMeteor\todos.meteor\local\build\server\server.js:286:12
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Programmi\Meteor\lib\node_modules\underscor
e\underscore.js:79:11)
    at run (F:\progettiMeteor\todos.meteor\local\build\server\server.js:227:7)
=> Exited with code: 1
=> Meteor server restarted

### 'F:\progettiMeteor\todos.meteor\local\build\app\packages\meteor\node_module

s\path'

F:\progettiMeteor\todos.meteor\local\build\server\server.js:325
  }).run();
     ^
Error: Can't find npm module 'sockjs'. Did you forget to call 'Npm.depends' in p
ackage.js within the 'livedata' package?
    at Object._.each.Npm.require (F:\progettiMeteor\todos.meteor\local\build\se
rver\server.js:259:23)
    at new Meteor._DdpStreamServer (app/packages/livedata/stream_server.js:18:20
)
    at new Meteor._LivedataServer (app/packages/livedata/livedata_server.js:1002
:24)
    at app/packages/livedata/server_convenience.js:8:19
    at F:\progettiMeteor\todos.meteor\local\build\server\server.js:286:12
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Programmi\Meteor\lib\node_modules\underscor
e\underscore.js:79:11)
    at run (F:\progettiMeteor\todos.meteor\local\build\server\server.js:227:7)
=> Exited with code: 1
=> Meteor server restarted

### 'F:\progettiMeteor\todos.meteor\local\build\app\packages\meteor\node_module

s\path'

F:\progettiMeteor\todos.meteor\local\build\server\server.js:325
  }).run();
     ^
Error: Can't find npm module 'sockjs'. Did you forget to call 'Npm.depends' in p
ackage.js within the 'livedata' package?
    at Object._.each.Npm.require (F:\progettiMeteor\todos.meteor\local\build\se
rver\server.js:259:23)
    at new Meteor._DdpStreamServer (app/packages/livedata/stream_server.js:18:20
)
    at new Meteor._LivedataServer (app/packages/livedata/livedata_server.js:1002
:24)
    at app/packages/livedata/server_convenience.js:8:19
    at F:\progettiMeteor\todos.meteor\local\build\server\server.js:286:12
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Programmi\Meteor\lib\node_modules\underscor
e\underscore.js:79:11)
    at run (F:\progettiMeteor\todos.meteor\local\build\server\server.js:227:7)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

**Comment by Gornova** [comment]
Note: works perfectly on windows 7 64 bit

**Comment by sdarnell** [comment]
Sorry I should have said that after the change to server.js, you may need to either create a new project or delete everything in the .meteor\local folder inside the project so that the server.js gets copied again.  "meteor reset" should also do that. But "rd .meteor\local /s/q" is what I use.

Alternatively, you could try modifying F:\progettiMeteor\todos.meteor\local\build\server\server.js but when I have done this in the past it gets overwritten whenever the re-bundling process kicks off.

I'm actually only interested in the new lines starting "###".

**Comment by sdarnell** [comment]
Good news is that I've managed to get an XP environment to try it on.
Bad news is that there's something very weird going on.

**Comment by sdarnell** [comment]
The weird bit is that the logging doesn't come out as expected - some kind of interaction between fibers and the vm module maybe. The underlying problem though seems to be that the npm directory (containing sockjs) in this case did not get copied during the bundling process. I'll investigate further tomorrow.

**Comment by Gornova** [comment]
thank for your time.

tip: write on documentation windows version supported and tested

**Comment by sdarnell** [comment]
I did some more investigation and have a couple of options for a solution. The root of the problem is the nightmare of symbolic links on windows. Vista+ has a command mklink, but XP doesn't have any built in way to create symlinks (directory junctions is what we need).

As a quick hack, you can replace the fs_symlinkSync() in %ProgramFiles%\Meteor\tools\bundler.js at line 52 with: 

```
var os = require("os");
var fs_symlinkSync = function (srcpath, dstpath) {
  if (process.platform === "win32") {
    if (/^5\./.test(os.release())) {
        // Windows XP doesn't have a built in tool for creating symlinks
        files.cp_r(srcpath, dstpath, {ignore: ignore_files});
    } else {
        // XXX Windows symlinks are broken in node 8.18, fixed in 9.11+
        // https://github.com/joyent/node/issues/4952
        exec('mklink /J "' + dstpath + '" "' + srcpath + '"');
    }
  } else {
    fs.symlinkSync(srcpath, dstpath);
  }
};
```

This works for me on XP Pro SP3 x64, though starting meteor is quite slow.
![image](https://f.cloud.github.com/assets/3684334/481971/50c3d68e-b880-11e2-9897-9860f55440f8.png)

I'll have a better fix later today in the form of a new MSI.

> tip: write on documentation windows version supported and tested

Good suggestion. I was thinking the same thing yesterday. Thanks.

**Comment by sdarnell** [comment]
Right, I've updated a new MSI (0.6.2.1-rev2). I retested it on XP and seems to work fine, I also added notes about platform support.

**Comment by Gornova** [comment]
works fine thanks!
