### ISSUE TITLE
Meteor won't run anymore

### ISSUE THREAD

**Issue by ghost** [sdarnell/meteor-win#41]
I installed Meteor a bit back (about a month) with the LaunchMeteor.exe bootstrapper. I left it for a bit since I couldn't do as much as I could've on my VM with Ubuntu.

Now when I run the command it says 'meteor is not recognized as a batch command'. But then when I run LaunchMeteor.exe again, it says 'you are not in a project directory'. So I tried to remove meteor with "rm -rf ~/.meteor/" and then ran LaunchMeteor.exe again, and same thing comes out of 'you are not in a project directory'. 

What can I do?

**Comment by sdarnell** [comment]
LaunchMeteor essentially does two things. It downloads and extracts the initial bundle, and adds that bundle to your PATH.

So the first problem you were seeing is either that the entry on your PATH disappeared, or more likely an issue with the cygwin shell. There is a known issue that cygwin doesn't correctly recognise .bat files, I'm amazed that this hasn't been fixed yet - but that's the situation.

The second thing you were trying to do was clear out the `.meteor` directory from your home directory. This was a good try, and would work on Unix, but on Windows the home directory isn't quite as simple as one location. The upshot is that the cygwin home directory points to the wrong place. Meteor actually resides in `%LOCALAPPDATA%\.meteor` but I don't know whether cygwin will map that correctly for you - so I would delete it from the Windows side. Also note that there are some very long paths in that tree - you may need to delete it with Windows Explorer.
For reference, you can override the use of `LOCALAPPDATA` if you specify `METEOR_WAREHOUSE_DIR`.

So, to recap.

I suspect everything is OK, and if you launched from a regular cmd or PowerShell prompt it would all be work. (Blame cygwin... seriously).

A work-around which may suit some people better is to take LaunchMeteor.exe and copy it to somewhere on your PATH as `meteor.exe`.  This avoids the issue with cygwin not recognising .bat extensions.  As you have seen already though may not have realised it, LaunchMeteor.exe simply tries to execute meteor if it is already downloaded (but in your case it failed because you weren't in an application directory).

You could remove `%LOCALAPPDATA%\.meteor` if you like and run `LaunchMeteor.exe`. This will do a re-install, but I suspect you will hit the same cygwin issues.

Hope this helps - if so, please close this issue, otherwise let me know how you get on and we'll diagnose further.

**Comment by ghost** [comment]
Thanks a lot for the reply!

I don't have cygwin installed, so still am baffled as to how this happened. I haven't touched my PATH variables either so again not sure.

I removed the %LOCALAPPDATA%.meteor folder and then re-ran LaunchMeteor.exe. It downloaded all the files and finished fine.

It now works perfectly again! Thanks a lot.

**Comment by sdarnell** [comment]
Just a quick update that the latest windows meteor now has a meteor.exe that sits along side the meteor.bat.
But note, you need to remove the old meteor and reinstall for it to appear.
