### ISSUE TITLE
Ctrl + C doesn't kill meteor app

### ISSUE THREAD

**Issue by anstarovoyt** [sdarnell/meteor-win#46]
Hello,
I am writing integration with meteor. I use 'meteor.bat' file for starting Meteor. My app tries to kill meteor process over send Ctrl+C signal to the process but meteor shows a confirmation 'Terminate batch job (Y/N)?' instead of killing. I think that a conformation for signal Ctrl + C is not expected behaviour.  Could you fix the problem?

**Comment by sdarnell** [comment]
It seems to be a common problem with batch files, and I am investigating the best solution, but I have a couple of short term options for you:
- The first is to use the `LaunchMeteor.exe` executable instead of `meteor.bat`.  This is an executable that attempts to download and install the meteor bootstrap package, but if it is already downloaded, it just does what `meteor.bat` does.
- The second is to stick `<nul` on the end of the command line, for example:

```
   meteor.bat <nul
```

Whilst the second solution still outputs the message, it doesn't block the process exiting.

For your information, the reason why I haven't made suggested using LaunchMeteor.exe always (renaming it to meteor.exe for convenience) is that it results in a relatively heavy weight .Net process hanging around. In the grand scheme of things it isn't that much though.

**Comment by anstarovoyt** [comment]
Thanks! I think your suggestion can help me.

**Comment by sdarnell** [comment]
I investigated quite a bit and there doesn't seem to be a way to prevent the prompt appearing in batch files. Although redirecting stdin from nul works around the issue, it prevents some of the useful meteor commands working - so isn't a viable general solution.  The only other option seems to be to patch `cmd.exe` which doesn't seem appropriate as a general solution either.

So I have decided to deliver `meteor.exe` along side the batch file, which does the same thing - it is actually a copy of `LaunchMeteor.exe`.

I have just released version 0.8.3 of meteor with the `meteor.exe`, but due to the way updates occur you won't get the meteor.exe automatically. One option is to just copy `LaunchMeteor.exe` to `meteor.exe` in `%LOCALAPPDATA%\.meteor`.

The other option is to delete or rename the `%LOCALAPPDATA%\.meteor` directory and then reinstall meteor using `LaunchMeteor.exe`. After that you should have a `meteor.exe` in the right place. 

Note that even though there is a meteor.bat and a `meteor.exe` in the same directory, Windows will prefer the `.exe` version. So you should be able to use just `meteor`.
