### ISSUE TITLE
Build meteor from scratch on Windows

### ISSUE THREAD

**Issue by peterennis** [sdarnell/meteor-win#50]
I have used your installer and launchmeteor also. It works nicely- Thx!
I am interested to build meteor from scratch on Windows 8.1
How do I get started?
Basic plan: get code => build => create msi

**Comment by sdarnell** [comment]
I'm no longer supporting the MSI based installer due to the 'warehouse' changes in Meteor.
LaunchMeteor.exe should work fine on Win8.1.

If you are experiencing issues I suspect they are related to fibers, and there are a few issues (and work-arounds) related to this if you scan the issues list.

Building from scratch involves cloning the github repo and having a look at the HowToBuild.md file.
If you really need an MSI, you may be able to disable the warehouse logic - but I'm afraid you are on your own at that point.

**Comment by peterennis** [comment]
OK.
Latest meteor is 0.9.0.1
You are at:
02-Aug-2014: Updated to 0.8.3 and added meteor.exe next to meteor.bat.

"cloning the github repo" - is the referring to your fork or is official windows support now moved elsewhere? Where would the best starting point be? I am not tied to the MSI track.

**Comment by sdarnell** [comment]
I strongly urge that you hold off as I'm in the middle of porting to 0.9.01 right now.
But it depends _why_ you want to build from scratch.

**Comment by peterennis** [comment]
I generally learn more about a system that I can build.
However I will wait for 9.0.1 as you suggest since
it has many changes.

Sent from Yahoo Mail on Android
