### ISSUE TITLE
No inidication of version for LaunchMeteor

### ISSUE THREAD

**Issue by peterennis** [sdarnell/meteor-win#52]
From here http://win.meteor.com/
Latest Meteor for Windows (exe bootstrapper) gives no indication of the current version.
I see a branch 0.9.0.1 but running lauchmeteor did not update from 0.8.3
When I went from 0.8.2 to 0.8.3 it was done using the 'meteor update' command.
How do I know when/how  to test this?

**Comment by idrakimuhamad** [comment]
You'll get a notification inside the CMD when the update is released. I believe @sdarnell still in the process of porting 0.9.0.1 to Windows. Please be patient.

**Comment by sdarnell** [comment]
Thanks @idrakimuhamad. Here's a bit of additional info:

LaunchMeteor.exe is not version specific - it will install the latest released version 'bootstrap' package.
Then internally the meteor command downloads and performs updates.

To see the version installed type `meteor --version`

Just because there is a 0.9.0.1 branch (or any other branch) does mean that it is working. There are HUGE changes to the meteor core in this release. While I have made some changes that are needed - things are not working, and there will be more changes to come.

I will be announcing on the meteor-talk google group when the release is ready to test, you might also want to 'watch' the github project to get other notifications too. When I release a new version, I also update: https://github.com/sdarnell/meteor/wiki/Windows
