### ISSUE TITLE
/sockjs/info 404 not found

### ISSUE THREAD

**Issue by kjohann** [sdarnell/meteor-win#8]
I'm using 0.6.3.1-rev3 of Meteor for Windows and have had no problems until resently. I played around with it a little trying to make some integration tests. For that purpose, I tried to launch meteor from my test.js file. This proved a little difficult, so I decided to launch the server manually instead. That's when I first got the following message in the browser console:

GET http://localhost:3000/sockjs/info 404 (Not Found)  sockjs-0.3.4.js:821

I figured it had to do with my fiddling, so I reinstalled Meteor, rebooted my computer and made a new project. Still, I get the same error. Any ideas?

The problem exists for Chrome, Firefox, Opera and IE10

**Comment by sdarnell** [comment]
The recent versions of meteor (not just Windows) now use web sockets by default (previously, I think long polling was the default). I have seen that some (non-Windows) users saw some issues when this happened, though it should eventually recover.

However, it isn't clear to me what I need to do to reproduce the issue you're seeing - maybe you could give detailed steps to explain what I need to do, and if it requires some application code to stimulate the issue, could you provide a simple form of that that I can run.

**Comment by kjohann** [comment]
Yes, I know about the WS support. That was unstable from the first day I used Meteor, but it didn't cause any problems. 

The problem here is that I really don't know what has happened, even though I know it has to do with something I have done (tried Meteor on another computer and it works fine).

What I did was the following:

While working I added a line to enable debugging to the /tools/run.js file at line 244:  nodeOptions.push('--debug');
This worked fine all the way, so I don't think it has anything to do with the problem.

When I tried to start Meteor from my testfile, I had to get some node modules like fiber and optimist. I required theese by using npm install from the .meteor/local/build/server folder of my app, but I can see that I have also installed fibers globally - don't know if that may have any effect.

After installing, Meteor complained about my Node version. Probably because when I ran the mocha test that required the server.js file (the one in my projects .meteor/local/build/server folder), it used the Node version I had installed before Meteor, not the version that came with it. So I updatet to the latest: 0.10.8. Still, this shouldn't cause any problems since it isn't used when I use the meteor command to start an app.

With these steps in place I got the test to run, but for some reason it just terminated after executing the line with require('.meteor/local/build/server/server.js'). So then I tried switching to using the server.js in the /tools/server folder. That gave an error because I hadn't set a env variable for the mongodb path, so I did this through the control panel (not through powershell). I didn't know the path, so I placed a console.log(process.env.MONGO_URL) in the /tools/server/server.js file at line 164. Then I ran a random app to see what url was used. Still, no problems (this was before setting the env variable of course). Before setting the env, I had also tried to hardcode the process.env.MONGO_URL variable, but since it didn't work, I removed it again.

After the above steps, my test ran, but with the same issue as before. It simply terminated after executing require('absolute_path_to/tools/server/server.js'), so then I decided to give up and just start the server manually before running the tests.

Then I first got a launch error telling me that it couldn't find a mongodb at the url I had set in my env variables. But after deleting it, meteor launched with no errors. However, when navigating to localhost:3000, I got the 404 error as described above. I tried reinstalling, but with no result.

What's weird is that a working Meteor app gets /sockjs/info with content-type application/json, but for me, it tries to get it as text/plain. That might just be because it can't find it though...

So that's all I did before it stopped working, and as I said, I have no idea why that may have broken Meteor on my computer.. But something obviously have :/

**Comment by sdarnell** [comment]
Thanks for the details.

My guess from what you say is that the problem is due to node picking up the wrong version of fibers. If you don't get the right version of fibers (and it isn't a released version), it is generally unstable and will often not work on windows exiting in the way you describe.

Now the problem is that node is a bit promiscuous when looking for modules, and I suspect that it is picking modules from the 'wrong' place in this instance.

Note that the meteor.bat file explicitly sets the NODE_PATH environment variable to point at the meteor versions, and if you're starting it yourself you will also need to specify that, e.g.:

```
 set NODE_PATH=%ProgramFiles(x86)%\lib\node_modules
```

Other things to try:
- Use the sysinternals procmon to monitor file activity to see where it is looking when loading modules, and confirm which files are being loaded.  http://technet.microsoft.com/en-gb/sysinternals/bb896645.aspx
- Rename/move your existing node installation so it doesn't interfere.
- Replace the globally installed fibers with the version in meteor.

I'm less clear what is happening with the sockjs, but my guess is that your other node modules includes a version of connect/express that isn't compatible with meteor. There have been some major changes in connect and meteor 0.6.3 is using a pretty ancient one - so I suspect that it is getting confused and trying to serve it in the wrong way.

The other thing to do is check whether you have any other environment variables that might impact node. I'm not sure what these might be, but hopefully they will be clear when you list your environment (just type `set`).  

Sorry, these are a bit of a stab in the dark ... but hopefully one of them might help point you in the right direction.

**Comment by kjohann** [comment]
Aha! I found another global node_modules folder in my Users/MyUserName folder (I also had one in the Users/MyUserName/AppData folder). I deleted the fibers module from here and that did it. It works like it did before now. The WebSocket support is close to none, but it was like that before too. I'm guessing that issue will go away with newer versions. 

Thanks for the help! And keep up the good work!
